//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_zhengshurecordsmall
    {
        public string id { get; set; }
        public string userid { get; set; }
        public string jobcategory { get; set; }
        public string nativephoto { get; set; }
        public string teshuphoto { get; set; }
        public string thirdphoto { get; set; }
        public string teshuzheng { get; set; }
        public string userphoto { get; set; }
    }
}
