//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_orginationinfo
    {
        public string id { get; set; }
        public string oracod { get; set; }
        public string oraname { get; set; }
        public Nullable<int> oralevel { get; set; }
        public string parentid { get; set; }
        public string machineid { get; set; }
        public Nullable<int> sortid { get; set; }
    }
}
