//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SY_DBLocalEntities : DbContext
    {
        public SY_DBLocalEntities()
            : base("name=SY_DBLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bas_consumerextend> bas_consumerextend { get; set; }
        public virtual DbSet<bas_doorinout> bas_doorinout { get; set; }
        public virtual DbSet<bas_livecount> bas_livecount { get; set; }
        public virtual DbSet<bas_orginationinfo> bas_orginationinfo { get; set; }
        public virtual DbSet<bas_saftycheck> bas_saftycheck { get; set; }
        public virtual DbSet<bas_saftystatus> bas_saftystatus { get; set; }
        public virtual DbSet<bas_XungengRecord> bas_XungengRecord { get; set; }
        public virtual DbSet<bas_zhengshurecord> bas_zhengshurecord { get; set; }
        public virtual DbSet<bas_zhengshurecordsmall> bas_zhengshurecordsmall { get; set; }
        public virtual DbSet<cod_keyval> cod_keyval { get; set; }
        public virtual DbSet<data_unlawrecord> data_unlawrecord { get; set; }
        public virtual DbSet<Doc> Doc { get; set; }
        public virtual DbSet<DocDetail> DocDetail { get; set; }
        public virtual DbSet<DocUsersDetail> DocUsersDetail { get; set; }
        public virtual DbSet<Loginer> Loginer { get; set; }
        public virtual DbSet<MessageInfo> MessageInfo { get; set; }
        public virtual DbSet<PrivilegeUploadLog> PrivilegeUploadLog { get; set; }
        public virtual DbSet<rel_userteacherecord> rel_userteacherecord { get; set; }
        public virtual DbSet<t_a_Holiday> t_a_Holiday { get; set; }
        public virtual DbSet<t_a_HolidayType> t_a_HolidayType { get; set; }
        public virtual DbSet<t_a_SystemParam> t_a_SystemParam { get; set; }
        public virtual DbSet<t_b_Consumer> t_b_Consumer { get; set; }
        public virtual DbSet<t_b_ControlHolidays> t_b_ControlHolidays { get; set; }
        public virtual DbSet<t_b_Controller> t_b_Controller { get; set; }
        public virtual DbSet<t_b_Controller_Zone> t_b_Controller_Zone { get; set; }
        public virtual DbSet<t_b_Controller_Zone4Operator> t_b_Controller_Zone4Operator { get; set; }
        public virtual DbSet<t_b_ControllerTaskList> t_b_ControllerTaskList { get; set; }
        public virtual DbSet<t_b_ControlSeg> t_b_ControlSeg { get; set; }
        public virtual DbSet<t_b_Door> t_b_Door { get; set; }
        public virtual DbSet<t_b_ElevatorGroup> t_b_ElevatorGroup { get; set; }
        public virtual DbSet<t_b_Floor> t_b_Floor { get; set; }
        public virtual DbSet<t_b_Group> t_b_Group { get; set; }
        public virtual DbSet<t_b_Group4Operator> t_b_Group4Operator { get; set; }
        public virtual DbSet<t_b_group4PCCheckAccess> t_b_group4PCCheckAccess { get; set; }
        public virtual DbSet<t_b_IDCard_Lost> t_b_IDCard_Lost { get; set; }
        public virtual DbSet<t_b_Reader> t_b_Reader { get; set; }
        public virtual DbSet<t_b_ReaderPassword> t_b_ReaderPassword { get; set; }
        public virtual DbSet<t_b_UserFloor> t_b_UserFloor { get; set; }
        public virtual DbSet<t_d_AttendenceData> t_d_AttendenceData { get; set; }
        public virtual DbSet<t_d_AttStatistic> t_d_AttStatistic { get; set; }
        public virtual DbSet<t_d_doorFirstCardUsers> t_d_doorFirstCardUsers { get; set; }
        public virtual DbSet<t_d_doorMoreCardsUsers> t_d_doorMoreCardsUsers { get; set; }
        public virtual DbSet<t_d_Leave> t_d_Leave { get; set; }
        public virtual DbSet<t_d_ManualCardRecord> t_d_ManualCardRecord { get; set; }
        public virtual DbSet<t_d_mapdoors> t_d_mapdoors { get; set; }
        public virtual DbSet<t_d_maps> t_d_maps { get; set; }
        public virtual DbSet<t_d_Meeting> t_d_Meeting { get; set; }
        public virtual DbSet<t_d_PatrolDetailData> t_d_PatrolDetailData { get; set; }
        public virtual DbSet<t_d_PatrolRouteDetail> t_d_PatrolRouteDetail { get; set; }
        public virtual DbSet<t_d_PatrolRouteList> t_d_PatrolRouteList { get; set; }
        public virtual DbSet<t_d_PatrolStatistic> t_d_PatrolStatistic { get; set; }
        public virtual DbSet<t_d_Privilege> t_d_Privilege { get; set; }
        public virtual DbSet<t_d_Privilege_Of_PrivilegeType> t_d_Privilege_Of_PrivilegeType { get; set; }
        public virtual DbSet<t_d_PrivilegeType> t_d_PrivilegeType { get; set; }
        public virtual DbSet<t_d_shift_AttReport> t_d_shift_AttReport { get; set; }
        public virtual DbSet<t_d_shift_AttStatistic> t_d_shift_AttStatistic { get; set; }
        public virtual DbSet<t_d_Shift_Work_Schedule> t_d_Shift_Work_Schedule { get; set; }
        public virtual DbSet<t_d_ShiftData> t_d_ShiftData { get; set; }
        public virtual DbSet<t_d_SwipeRecord> t_d_SwipeRecord { get; set; }
        public virtual DbSet<t_s_Operator> t_s_Operator { get; set; }
        public virtual DbSet<t_s_OperatorPrivilege> t_s_OperatorPrivilege { get; set; }
        public virtual DbSet<t_s_wglog> t_s_wglog { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Templete> Templete { get; set; }
        public virtual DbSet<TempleteDetail> TempleteDetail { get; set; }
        public virtual DbSet<UnitInfo> UnitInfo { get; set; }
        public virtual DbSet<UserConsumer> UserConsumer { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WatchingLog> WatchingLog { get; set; }
        public virtual DbSet<XungengRecord> XungengRecord { get; set; }
        public virtual DbSet<bas_pxcontent> bas_pxcontent { get; set; }
        public virtual DbSet<DocUsersDetailbk07081249> DocUsersDetailbk07081249 { get; set; }
        public virtual DbSet<MessageImageInfo> MessageImageInfo { get; set; }
        public virtual DbSet<t_a_Attendence> t_a_Attendence { get; set; }
        public virtual DbSet<t_a_Shift_Attendence> t_a_Shift_Attendence { get; set; }
        public virtual DbSet<t_b_Camera> t_b_Camera { get; set; }
        public virtual DbSet<t_b_CameraTriggerSource> t_b_CameraTriggerSource { get; set; }
        public virtual DbSet<t_b_Consumer_Delete> t_b_Consumer_Delete { get; set; }
        public virtual DbSet<t_b_Consumer_Other> t_b_Consumer_Other { get; set; }
        public virtual DbSet<t_b_Group4Meal> t_b_Group4Meal { get; set; }
        public virtual DbSet<t_b_MealSetup> t_b_MealSetup { get; set; }
        public virtual DbSet<t_b_ShiftSet> t_b_ShiftSet { get; set; }
        public virtual DbSet<t_d_MeetingAdr> t_d_MeetingAdr { get; set; }
        public virtual DbSet<t_d_MeetingConsumer> t_d_MeetingConsumer { get; set; }
        public virtual DbSet<t_d_PatrolPlanData> t_d_PatrolPlanData { get; set; }
        public virtual DbSet<t_d_Reader4Meal> t_d_Reader4Meal { get; set; }
        public virtual DbSet<t_d_Reader4Meeting> t_d_Reader4Meeting { get; set; }
        public virtual DbSet<UserInfoDeleted> UserInfoDeleted { get; set; }
    }
}
