//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfo
    {
        public int MessageID { get; set; }
        public string MessageType { get; set; }
        public string MessageTitle { get; set; }
        public string MessageHTMLBody { get; set; }
        public string MessageTEXTBody { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateMan { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateMan { get; set; }
    }
}
