//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_MealSetup
    {
        public int f_ID { get; set; }
        public Nullable<int> f_Value { get; set; }
        public Nullable<System.DateTime> f_BeginHMS { get; set; }
        public Nullable<System.DateTime> f_EndHMS { get; set; }
        public Nullable<decimal> f_ParamVal { get; set; }
        public string f_Notes { get; set; }
    }
}
