//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_ShiftSet
    {
        public int f_ShiftID { get; set; }
        public string f_ShiftName { get; set; }
        public Nullable<int> f_ReadTimes { get; set; }
        public Nullable<System.DateTime> f_OnDuty1 { get; set; }
        public Nullable<System.DateTime> f_OffDuty1 { get; set; }
        public Nullable<System.DateTime> f_OnDuty2 { get; set; }
        public Nullable<System.DateTime> f_OffDuty2 { get; set; }
        public Nullable<System.DateTime> f_OnDuty3 { get; set; }
        public Nullable<System.DateTime> f_OffDuty3 { get; set; }
        public Nullable<System.DateTime> f_OnDuty4 { get; set; }
        public Nullable<System.DateTime> f_OffDuty4 { get; set; }
        public Nullable<int> f_bOvertimeShift { get; set; }
        public string f_Notes { get; set; }
    }
}
