//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_Door
    {
        public int f_DoorID { get; set; }
        public int f_ControllerID { get; set; }
        public byte f_DoorNO { get; set; }
        public string f_DoorName { get; set; }
        public int f_DoorControl { get; set; }
        public int f_DoorDelay { get; set; }
        public int f_DoorEnabled { get; set; }
        public int f_MoreCards_Total { get; set; }
        public int f_MoreCards_Grp1 { get; set; }
        public int f_MoreCards_Grp2 { get; set; }
        public int f_MoreCards_Grp3 { get; set; }
        public int f_MoreCards_Grp4 { get; set; }
        public int f_MoreCards_Grp5 { get; set; }
        public int f_MoreCards_Grp6 { get; set; }
        public int f_MoreCards_Grp7 { get; set; }
        public int f_MoreCards_Grp8 { get; set; }
        public int f_MoreCards_Option { get; set; }
        public int f_FirstCard_Enabled { get; set; }
        public int f_FirstCard_Weekday { get; set; }
        public string f_FirstCard_BeginHMS { get; set; }
        public int f_FirstCard_BeginControl { get; set; }
        public string f_FirstCard_EndHMS { get; set; }
        public int f_FirstCard_EndControl { get; set; }
    }
}
