//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_group4PCCheckAccess
    {
        public int f_Id { get; set; }
        public int f_GroupID { get; set; }
        public int f_GroupType { get; set; }
        public int f_CheckAccessActive { get; set; }
        public int f_MoreCards { get; set; }
        public string f_SoundFileName { get; set; }
        public string f_Notes { get; set; }
    }
}
