//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_Camera
    {
        public int f_CameraId { get; set; }
        public string f_CameraName { get; set; }
        public string f_CameraIP { get; set; }
        public int f_CameraPort { get; set; }
        public int f_CameraChannel { get; set; }
        public int f_Enabled { get; set; }
        public string f_CameraUser { get; set; }
        public string f_CameraPassword { get; set; }
        public int f_Type { get; set; }
        public string f_Notes { get; set; }
    }
}
