//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_Consumer_Other
    {
        public int f_ConsumerID { get; set; }
        public string f_Note { get; set; }
        public string f_WorkNo { get; set; }
        public string f_Title { get; set; }
        public string f_Culture { get; set; }
        public string f_Hometown { get; set; }
        public string f_Birthday { get; set; }
        public string f_Marriage { get; set; }
        public string f_JoinDate { get; set; }
        public string f_LeaveDate { get; set; }
        public string f_CertificateType { get; set; }
        public string f_CertificateID { get; set; }
        public string f_SocialInsuranceNo { get; set; }
        public string f_Addr { get; set; }
        public string f_Postcode { get; set; }
        public string f_Sex { get; set; }
        public string f_Nationality { get; set; }
        public string f_Religion { get; set; }
        public string f_EnglishName { get; set; }
        public string f_Mobile { get; set; }
        public string f_HomePhone { get; set; }
        public string f_Telephone { get; set; }
        public string f_Email { get; set; }
        public string f_Political { get; set; }
        public string f_CorporationName { get; set; }
        public string f_TechGrade { get; set; }
    }
}
