//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_b_Controller
    {
        public int f_ControllerID { get; set; }
        public int f_ControllerNO { get; set; }
        public int f_ControllerSN { get; set; }
        public byte f_Enabled { get; set; }
        public string f_IP { get; set; }
        public int f_PORT { get; set; }
        public string f_Note { get; set; }
        public string f_DoorNames { get; set; }
        public int f_ZoneID { get; set; }
        public int f_AntiBack { get; set; }
        public int f_InterLock { get; set; }
        public int f_MoreCards_GoInOut { get; set; }
        public int f_DoorInvalidOpen { get; set; }
        public int f_DoorOpenTooLong { get; set; }
        public int f_ForceWarn { get; set; }
        public int f_InvalidCardWarn { get; set; }
        public string f_PeripheralControl { get; set; }
        public string f_lastDelAddDateTime { get; set; }
        public int f_lastDelAddConsuemrsTotal { get; set; }
        public string f_lastDelAddAndUploadDateTime { get; set; }
        public int f_lastDelAddAndUploadConsuemrsTotal { get; set; }
        public string f_lastConsoleUploadDateTime { get; set; }
        public int f_lastConsoleUploadConsuemrsTotal { get; set; }
        public int f_lastConsoleUploadPrivilege { get; set; }
        public int f_lastConsoleUploadValidPrivilege { get; set; }
    }
}
