//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_Meeting
    {
        public string f_MeetingNO { get; set; }
        public string f_MeetingName { get; set; }
        public string f_MeetingAdr { get; set; }
        public System.DateTime f_MeetingDateTime { get; set; }
        public System.DateTime f_SignStartTime { get; set; }
        public System.DateTime f_SignEndTime { get; set; }
        public string f_Content { get; set; }
        public string f_Notes { get; set; }
    }
}
