//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_shift_AttReport
    {
        public int f_RecID { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public Nullable<System.DateTime> f_ShiftDate { get; set; }
        public Nullable<int> f_ShiftID { get; set; }
        public Nullable<int> f_ReadTimes { get; set; }
        public Nullable<System.DateTime> f_OnDuty1 { get; set; }
        public string f_OnDuty1AttDesc { get; set; }
        public string f_OnDuty1CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OffDuty1 { get; set; }
        public string f_OffDuty1AttDesc { get; set; }
        public string f_OffDuty1CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OnDuty2 { get; set; }
        public string f_OnDuty2AttDesc { get; set; }
        public string f_OnDuty2CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OffDuty2 { get; set; }
        public string f_OffDuty2AttDesc { get; set; }
        public string f_OffDuty2CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OnDuty3 { get; set; }
        public string f_OnDuty3AttDesc { get; set; }
        public string f_OnDuty3CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OffDuty3 { get; set; }
        public string f_OffDuty3AttDesc { get; set; }
        public string f_OffDuty3CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OnDuty4 { get; set; }
        public string f_OnDuty4AttDesc { get; set; }
        public string f_OnDuty4CardRecordDesc { get; set; }
        public Nullable<System.DateTime> f_OffDuty4 { get; set; }
        public string f_OffDuty4AttDesc { get; set; }
        public string f_OffDuty4CardRecordDesc { get; set; }
        public Nullable<decimal> f_LateMinutes { get; set; }
        public Nullable<decimal> f_LeaveEarlyMinutes { get; set; }
        public Nullable<decimal> f_OvertimeHours { get; set; }
        public Nullable<decimal> f_AbsenceDays { get; set; }
        public Nullable<int> f_NotReadCardCount { get; set; }
        public Nullable<int> f_bOvertimeShift { get; set; }
    }
}
