//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_PatrolPlanData
    {
        public int f_RecID { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public string f_DateYM { get; set; }
        public Nullable<int> f_RouteID_01 { get; set; }
        public Nullable<int> f_RouteID_02 { get; set; }
        public Nullable<int> f_RouteID_03 { get; set; }
        public Nullable<int> f_RouteID_04 { get; set; }
        public Nullable<int> f_RouteID_05 { get; set; }
        public Nullable<int> f_RouteID_06 { get; set; }
        public Nullable<int> f_RouteID_07 { get; set; }
        public Nullable<int> f_RouteID_08 { get; set; }
        public Nullable<int> f_RouteID_09 { get; set; }
        public Nullable<int> f_RouteID_10 { get; set; }
        public Nullable<int> f_RouteID_11 { get; set; }
        public Nullable<int> f_RouteID_12 { get; set; }
        public Nullable<int> f_RouteID_13 { get; set; }
        public Nullable<int> f_RouteID_14 { get; set; }
        public Nullable<int> f_RouteID_15 { get; set; }
        public Nullable<int> f_RouteID_16 { get; set; }
        public Nullable<int> f_RouteID_17 { get; set; }
        public Nullable<int> f_RouteID_18 { get; set; }
        public Nullable<int> f_RouteID_19 { get; set; }
        public Nullable<int> f_RouteID_20 { get; set; }
        public Nullable<int> f_RouteID_21 { get; set; }
        public Nullable<int> f_RouteID_22 { get; set; }
        public Nullable<int> f_RouteID_23 { get; set; }
        public Nullable<int> f_RouteID_24 { get; set; }
        public Nullable<int> f_RouteID_25 { get; set; }
        public Nullable<int> f_RouteID_26 { get; set; }
        public Nullable<int> f_RouteID_27 { get; set; }
        public Nullable<int> f_RouteID_28 { get; set; }
        public Nullable<int> f_RouteID_29 { get; set; }
        public Nullable<int> f_RouteID_30 { get; set; }
        public Nullable<int> f_RouteID_31 { get; set; }
        public Nullable<System.DateTime> f_LogDate { get; set; }
        public string f_Notes { get; set; }
    }
}
