//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_SwipeRecord
    {
        public int f_RecID { get; set; }
        public System.DateTime f_ReadDate { get; set; }
        public long f_CardNO { get; set; }
        public int f_ConsumerID { get; set; }
        public byte f_Character { get; set; }
        public byte f_InOut { get; set; }
        public byte f_Status { get; set; }
        public byte f_RecOption { get; set; }
        public int f_ControllerSN { get; set; }
        public int f_ReaderID { get; set; }
        public byte f_ReaderNO { get; set; }
        public int f_RecordFlashLoc { get; set; }
        public string f_RecordAll { get; set; }
        public System.DateTime f_Modified { get; set; }
    }
}
