//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_doorMoreCardsUsers
    {
        public int f_doorMoreCardsUsersId { get; set; }
        public int f_DoorID { get; set; }
        public int f_MoreCards_GrpID { get; set; }
        public int f_ConsumerID { get; set; }
    }
}
