//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_ShiftData
    {
        public int f_RecID { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public string f_DateYM { get; set; }
        public Nullable<int> f_ShiftID_01 { get; set; }
        public Nullable<int> f_ShiftID_02 { get; set; }
        public Nullable<int> f_ShiftID_03 { get; set; }
        public Nullable<int> f_ShiftID_04 { get; set; }
        public Nullable<int> f_ShiftID_05 { get; set; }
        public Nullable<int> f_ShiftID_06 { get; set; }
        public Nullable<int> f_ShiftID_07 { get; set; }
        public Nullable<int> f_ShiftID_08 { get; set; }
        public Nullable<int> f_ShiftID_09 { get; set; }
        public Nullable<int> f_ShiftID_10 { get; set; }
        public Nullable<int> f_ShiftID_11 { get; set; }
        public Nullable<int> f_ShiftID_12 { get; set; }
        public Nullable<int> f_ShiftID_13 { get; set; }
        public Nullable<int> f_ShiftID_14 { get; set; }
        public Nullable<int> f_ShiftID_15 { get; set; }
        public Nullable<int> f_ShiftID_16 { get; set; }
        public Nullable<int> f_ShiftID_17 { get; set; }
        public Nullable<int> f_ShiftID_18 { get; set; }
        public Nullable<int> f_ShiftID_19 { get; set; }
        public Nullable<int> f_ShiftID_20 { get; set; }
        public Nullable<int> f_ShiftID_21 { get; set; }
        public Nullable<int> f_ShiftID_22 { get; set; }
        public Nullable<int> f_ShiftID_23 { get; set; }
        public Nullable<int> f_ShiftID_24 { get; set; }
        public Nullable<int> f_ShiftID_25 { get; set; }
        public Nullable<int> f_ShiftID_26 { get; set; }
        public Nullable<int> f_ShiftID_27 { get; set; }
        public Nullable<int> f_ShiftID_28 { get; set; }
        public Nullable<int> f_ShiftID_29 { get; set; }
        public Nullable<int> f_ShiftID_30 { get; set; }
        public Nullable<int> f_ShiftID_31 { get; set; }
        public Nullable<System.DateTime> f_LogDate { get; set; }
        public string f_Notes { get; set; }
    }
}
