//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_shift_AttStatistic
    {
        public int f_RecID { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public Nullable<System.DateTime> f_AttDateStart { get; set; }
        public Nullable<System.DateTime> f_AttDateEnd { get; set; }
        public Nullable<int> f_DayShouldWork { get; set; }
        public Nullable<decimal> f_LateMinutes { get; set; }
        public Nullable<int> f_LateCount { get; set; }
        public Nullable<decimal> f_LeaveEarlyMinutes { get; set; }
        public Nullable<int> f_LeaveEarlyCount { get; set; }
        public Nullable<decimal> f_OvertimeHours { get; set; }
        public Nullable<decimal> f_AbsenceDays { get; set; }
        public Nullable<int> f_NotReadCardCount { get; set; }
        public Nullable<int> f_ManualReadTimesCount { get; set; }
        public string f_SpecialType1 { get; set; }
        public string f_SpecialType2 { get; set; }
        public string f_SpecialType3 { get; set; }
        public string f_SpecialType4 { get; set; }
        public string f_SpecialType5 { get; set; }
        public string f_SpecialType6 { get; set; }
        public string f_SpecialType7 { get; set; }
        public string f_SpecialType8 { get; set; }
        public string f_SpecialType9 { get; set; }
        public string f_SpecialType10 { get; set; }
        public string f_SpecialType11 { get; set; }
        public string f_SpecialType12 { get; set; }
        public string f_SpecialType13 { get; set; }
        public string f_SpecialType14 { get; set; }
        public string f_SpecialType15 { get; set; }
        public string f_SpecialType16 { get; set; }
        public string f_SpecialType17 { get; set; }
        public string f_SpecialType18 { get; set; }
        public string f_SpecialType19 { get; set; }
        public string f_SpecialType20 { get; set; }
        public string f_SpecialType21 { get; set; }
        public string f_SpecialType22 { get; set; }
        public string f_SpecialType23 { get; set; }
        public string f_SpecialType24 { get; set; }
        public string f_SpecialType25 { get; set; }
        public string f_SpecialType26 { get; set; }
        public string f_SpecialType27 { get; set; }
        public string f_SpecialType28 { get; set; }
        public string f_SpecialType29 { get; set; }
        public string f_SpecialType30 { get; set; }
        public string f_SpecialType31 { get; set; }
        public string f_SpecialType32 { get; set; }
        public int f_DayRealWork { get; set; }
    }
}
