//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_Shift_Work_Schedule
    {
        public int f_RecID { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public Nullable<System.DateTime> f_ShiftDate { get; set; }
        public Nullable<int> f_ShiftID { get; set; }
        public Nullable<int> f_ReadTimes { get; set; }
        public Nullable<System.DateTime> f_PlanTime { get; set; }
        public Nullable<int> f_TimeSeg { get; set; }
        public Nullable<System.DateTime> f_WorkTime { get; set; }
        public string f_AttDesc { get; set; }
        public string f_CardRecordDesc { get; set; }
        public Nullable<int> f_Duration { get; set; }
        public Nullable<int> f_bOvertimeShift { get; set; }
    }
}
