//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_MeetingConsumer
    {
        public int f_Id { get; set; }
        public string f_MeetingNO { get; set; }
        public int f_ConsumerID { get; set; }
        public int f_MeetingIdentity { get; set; }
        public string f_Seat { get; set; }
        public int f_SignWay { get; set; }
        public Nullable<System.DateTime> f_SignRealTime { get; set; }
        public int f_RecID { get; set; }
        public string f_Notes { get; set; }
    }
}
