//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_PatrolRouteDetail
    {
        public int f_RecId { get; set; }
        public int f_RouteID { get; set; }
        public int f_Sn { get; set; }
        public Nullable<int> f_ReaderID { get; set; }
        public string f_patroltime { get; set; }
        public Nullable<int> f_NextDay { get; set; }
    }
}
