//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_d_PatrolDetailData
    {
        public int f_RecId { get; set; }
        public Nullable<int> f_ConsumerID { get; set; }
        public Nullable<System.DateTime> f_PatrolDate { get; set; }
        public Nullable<int> f_RouteID { get; set; }
        public Nullable<int> f_ReaderID { get; set; }
        public Nullable<System.DateTime> f_PlanPatrolTime { get; set; }
        public Nullable<System.DateTime> f_RealPatrolTime { get; set; }
        public Nullable<int> f_EventDesc { get; set; }
    }
}
