//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_s_Operator
    {
        public int f_OperatorID { get; set; }
        public string f_OperatorName { get; set; }
        public string f_Password { get; set; }
        public string f_OperatePrivilege { get; set; }
        public string f_Notes { get; set; }
    }
}
