//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_s_OperatorPrivilege
    {
        public int f_OperatorID { get; set; }
        public int f_FunctionID { get; set; }
        public string f_FunctionName { get; set; }
        public string f_FunctionDisplayName { get; set; }
        public int f_ReadOnly { get; set; }
        public int f_FullControl { get; set; }
    }
}
