//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitInfo
    {
        public int UnitID { get; set; }
        public string UnitNo { get; set; }
        public string UnitName { get; set; }
        public string ContactMan { get; set; }
        public string ContactTel { get; set; }
    }
}
