//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabinbow.EfModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoDeleted
    {
        public int ID { get; set; }
        public string CardNo { get; set; }
        public string Name { get; set; }
        public byte[] UserPhoto { get; set; }
        public byte[] BarCode { get; set; }
        public string BarCodeStr { get; set; }
        public Nullable<System.DateTime> TrainDate { get; set; }
        public Nullable<decimal> TrainLength { get; set; }
        public string UserScore { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> UnitID { get; set; }
    }
}
